sudo: false
language: node_js
node_js:
- '7.4'
before_script:
  - npm install -g frontplate-cli
script:
  - npm run svgsprite
  - frp task clean
  - frp task sprite
  - frp task copy
  - frp task html
  - frp task script
  - frp task style
